# Generated by Django 2.1.2 on 2018-10-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='initials',
            field=models.CharField(max_length=9),
        ),
    ]
